# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=45, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
